version: "3"

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    command: mongod --auth
    environment:
      MONGO_INITDB_ROOT_USERNAME: kirthi
      MONGO_INITDB_ROOT_PASSWORD: kirthi
      MONGO_INITDB_DATABASE: kithidb
      MONGODB_DATA_DIR: /data/db
      MONGODB_LOG_DIR: /dev/null
    ports:
      - "27017:27017"
    volumes:
      - mongodbdata:/db

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: kirthiserver
    hostname: kithiserver
    restart: unless-stopped
    image: flask
    ports:
      - "5000:5000"
    volumes:
      - flask:/var/www
    environment:
      APP_ENV: "dev"
      APP_PORT: 5000
      APP_DEBUG: "True"
      MONGODB_DATABASE: kirthidb
      MONGODB_USERNAME: kirthi
      MONGODB_PASSWORD: kirthi
      MONGODB_HOSTNAME: mongodb
    depends_on:
      - mongodb

volumes:
  mongodbdata:
  flask:
